/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Western bluebird.glb -o src/components/WesternBluebird.jsx -r public -k
Western bluebird by Poly by Google [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/cdcl5UwlYWd)
*/

import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";
import React, { useRef } from "react";
import { useExplode } from "../hooks/useExplode";

export function WesternBluebird(props) {
  const { nodes, materials } = useGLTF("/models/Western bluebird.glb");
  const group = useRef();
  const { bluebirddistance } = useControls({
    bluebirddistance: {
      value: 2.4,
      min: 0,
      max: 10,
    },
  });
  useExplode(group, {
    distance: bluebirddistance,
    rotationEnabled: true,
  });
  return (
    <group {...props} dispose={null} ref={group}>
      <mesh
        name="origin"
        geometry={nodes.origin.geometry}
        material={materials["WesternBluebird_Mat.001"]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell001"
        geometry={nodes.WesternBluebird_Mesh_cell001.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[0.162, 0.329, 0.301]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell003"
        geometry={nodes.WesternBluebird_Mesh_cell003.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.009, -0.397, -0.971]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell004"
        geometry={nodes.WesternBluebird_Mesh_cell004.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.058, 0.032, 0.398]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell007"
        geometry={nodes.WesternBluebird_Mesh_cell007.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.016, 0.247, 0.411]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell010"
        geometry={nodes.WesternBluebird_Mesh_cell010.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.296, 0.022, -0.035]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell011"
        geometry={nodes.WesternBluebird_Mesh_cell011.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.087, -0.458, -0.048]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell016"
        geometry={nodes.WesternBluebird_Mesh_cell016.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.004, -0.148, -0.591]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell018"
        geometry={nodes.WesternBluebird_Mesh_cell018.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.217, 0.203, 0.196]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell019"
        geometry={nodes.WesternBluebird_Mesh_cell019.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.008, -0.31, -0.739]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell021"
        geometry={nodes.WesternBluebird_Mesh_cell021.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.202, -0.199, -0.308]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell022"
        geometry={nodes.WesternBluebird_Mesh_cell022.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.092, -0.438, 0.056]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell023"
        geometry={nodes.WesternBluebird_Mesh_cell023.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[0.219, -0.21, -0.213]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell026"
        geometry={nodes.WesternBluebird_Mesh_cell026.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[0.211, 0.119, -0.02]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell027"
        geometry={nodes.WesternBluebird_Mesh_cell027.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[0.076, -0.285, -0.749]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell028"
        geometry={nodes.WesternBluebird_Mesh_cell028.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[0.085, -0.373, 0.005]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell029"
        geometry={nodes.WesternBluebird_Mesh_cell029.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.081, 0.175, -0.097]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell030"
        geometry={nodes.WesternBluebird_Mesh_cell030.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.091, -0.278, 0.163]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell031"
        geometry={nodes.WesternBluebird_Mesh_cell031.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.07, -0.318, -0.064]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell032"
        geometry={nodes.WesternBluebird_Mesh_cell032.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.009, 0.411, 0.421]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell034"
        geometry={nodes.WesternBluebird_Mesh_cell034.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.018, -0.28, -0.401]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell036"
        geometry={nodes.WesternBluebird_Mesh_cell036.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.197, -0.215, 0.085]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell037"
        geometry={nodes.WesternBluebird_Mesh_cell037.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[0.249, -0.124, 0.044]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell038"
        geometry={nodes.WesternBluebird_Mesh_cell038.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.098, -0.074, -0.149]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell040"
        geometry={nodes.WesternBluebird_Mesh_cell040.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.057, -0.056, 0.268]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell042"
        geometry={nodes.WesternBluebird_Mesh_cell042.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.001, 0.38, 0.603]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell043"
        geometry={nodes.WesternBluebird_Mesh_cell043.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[0.182, -0.287, 0.006]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell044"
        geometry={nodes.WesternBluebird_Mesh_cell044.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[0.321, -0.012, -0.026]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell045"
        geometry={nodes.WesternBluebird_Mesh_cell045.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[0.116, -0.318, -0.137]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell046"
        geometry={nodes.WesternBluebird_Mesh_cell046.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.097, -0.309, -0.23]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell048"
        geometry={nodes.WesternBluebird_Mesh_cell048.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[0.126, -0.146, -0.458]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell049"
        geometry={nodes.WesternBluebird_Mesh_cell049.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[0.185, -0.006, -0.256]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell051"
        geometry={nodes.WesternBluebird_Mesh_cell051.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[0.038, 0.361, 0.142]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell052"
        geometry={nodes.WesternBluebird_Mesh_cell052.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[0.03, -0.203, 0.09]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell053"
        geometry={nodes.WesternBluebird_Mesh_cell053.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.146, -0.312, 0.028]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell054"
        geometry={nodes.WesternBluebird_Mesh_cell054.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[0.23, 0.239, 0.143]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell055"
        geometry={nodes.WesternBluebird_Mesh_cell055.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[0.108, -0.283, 0.113]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell056"
        geometry={nodes.WesternBluebird_Mesh_cell056.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.1, -0.225, -0.543]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell057"
        geometry={nodes.WesternBluebird_Mesh_cell057.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[0.164, 0.102, 0.273]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell059"
        geometry={nodes.WesternBluebird_Mesh_cell059.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.069, -0.098, -0.52]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell061"
        geometry={nodes.WesternBluebird_Mesh_cell061.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.267, -0.184, -0.124]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell063"
        geometry={nodes.WesternBluebird_Mesh_cell063.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.166, 0.055, -0.269]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell064"
        geometry={nodes.WesternBluebird_Mesh_cell064.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.253, -0.05, 0.144]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell065"
        geometry={nodes.WesternBluebird_Mesh_cell065.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.058, -0.462, 0.106]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell066"
        geometry={nodes.WesternBluebird_Mesh_cell066.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.313, -0.132, -0.216]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell067"
        geometry={nodes.WesternBluebird_Mesh_cell067.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[0.101, 0.105, -0.296]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell071"
        geometry={nodes.WesternBluebird_Mesh_cell071.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.093, -0.028, -0.41]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell072"
        geometry={nodes.WesternBluebird_Mesh_cell072.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[0.203, -0.199, -0.437]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell073"
        geometry={nodes.WesternBluebird_Mesh_cell073.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.295, 0.083, 0.206]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell075"
        geometry={nodes.WesternBluebird_Mesh_cell075.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[0.054, -0.243, -0.276]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell005"
        geometry={nodes.WesternBluebird_Mesh_cell005.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.092, -0.457, 0.141]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell006"
        geometry={nodes.WesternBluebird_Mesh_cell006.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.058, -0.459, 0.134]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell008"
        geometry={nodes.WesternBluebird_Mesh_cell008.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[-0.128, -0.457, 0.147]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell009"
        geometry={nodes.WesternBluebird_Mesh_cell009.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[0.107, -0.455, 0.055]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell012"
        geometry={nodes.WesternBluebird_Mesh_cell012.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[0.087, -0.456, -0.035]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell013"
        geometry={nodes.WesternBluebird_Mesh_cell013.geometry}
        material={materials["WesternBluebird_Mat.001"]}
        position={[0.09, -0.455, 0.114]}
      />
    </group>
  );
}

useGLTF.preload("/models/Western bluebird.glb");
